HTTP_CODE_SUCCESS = 200
HTTP_CODE_CREATED = 201
HTTP_CODE_INVALID_DATA = 400
HTTP_CODE_NOT_AUTHENTICATED = 401  # לא נעשה לוגין
HTTP_CODE_FORBIDDEN = 403  # אין לך הרשאות
HTTP_CODE_NOT_FOUND = 404
HTTP_CODE_STATE_CONFLICT = 404
HTTP_CODE_SERVER_ERROR = 500